FROM vllm/vllm-openai:v0.21.0-cu129

# 1. 安装中文字体、curl 等工具
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        fontconfig \
        fonts-noto-cjk \
        curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 2. 使用 uv 极速安装 Python 依赖
RUN python3 -m pip install --upgrade pip uv && \
    ln -s $(which python3) /usr/local/bin/python && \
    uv pip install --system -U "mineru[all]"
